### ISSUE TITLE
Add terragrunt_version 'latest'

### ISSUE THREAD

**Issue by ahummel25** [autero1/action-terragrunt#8]
Hello,

Thanks for creating this action! Super helpful.

Would it be possible to add functionality where the terragrunt version would always be the latest?

```yml
- name: Setup Terragrunt
  uses: autero1/action-terragrunt@v1.0.0
  with:
    terragrunt_version: 'latest'
```

Something like the above?

Thanks!
